# Generated by Django 4.0.6 on 2022-07-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_botuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
