# Generated by Django 4.0.6 on 2022-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_botuser_city_alter_botuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
