# Generated by Django 4.0.6 on 2022-07-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_botuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.RemoveField(
            model_name='engine',
            name='title',
        ),
        migrations.AddField(
            model_name='engine',
            name='power',
            field=models.IntegerField(null=True, verbose_name='Мощность'),
        ),
        migrations.AddField(
            model_name='engine',
            name='type_fuel',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='engine',
            name='volume',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя аккаунта'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя (заполненное)'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone',
            field=models.BigIntegerField(null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='Индент. пользователя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.engine', verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='expenditure',
            field=models.CharField(max_length=255, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.transmission', verbose_name='Трансмиссия'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wd', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='city',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='is_visible',
            field=models.BooleanField(verbose_name='Отображается'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='model',
            name='body',
            field=models.CharField(max_length=255, verbose_name='Тело'),
        ),
        migrations.AlterField(
            model_name='model',
            name='is_visible',
            field=models.BooleanField(verbose_name='Отображается'),
        ),
        migrations.AlterField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mark', verbose_name='Идент. марки'),
        ),
        migrations.AlterField(
            model_name='model',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='model',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.URLField(verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='set',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.model', verbose_name='Идент. модели'),
        ),
        migrations.AlterField(
            model_name='set',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wd',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
