# Generated by Django 4.0.6 on 2022-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_model_options_remove_engine_title_engine_power_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='model',
            name='price',
            field=models.BigIntegerField(verbose_name='Цена'),
        ),
    ]
