# Generated by Django 4.0.6 on 2022-07-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_set_options_alter_model_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.URLField(verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='set',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.model', verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='SetTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.set')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='SetEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.engine')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.set')),
            ],
        ),
    ]
