# Generated by Django 4.1 on 2022-08-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_newcar_question_alter_entry_address_alter_entry_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.set', verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
