# Generated by Django 4.1 on 2022-08-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_webuser_alter_car_set_alter_color_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webuser',
            options={'verbose_name': 'Пользователь сайта', 'verbose_name_plural': 'Пользователи сайта'},
        ),
        migrations.AlterField(
            model_name='webuser',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Блокировка'),
        ),
    ]
