# Generated by Django 4.1 on 2022-08-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_webuser_options_alter_webuser_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Имя пользователя')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP адрес')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Телефон')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.botuser', verbose_name='Пользователь сайта')),
            ],
            options={
                'verbose_name': 'Вопрос пользователя',
                'verbose_name_plural': 'Вопросы пользователей',
            },
        ),
    ]
