# Generated by Django 4.1 on 2022-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
