# Generated by Django 4.1 on 2022-10-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='car',
            name='expenditure',
            field=models.CharField(max_length=255, null=True, verbose_name='Расход'),
        ),
    ]
