# Generated by Django 4.1 on 2022-10-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_distributor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
