# Generated by Django 4.1 on 2022-10-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('parser', 'With the help to parser'), ('distributor', 'With the help to distributor')], max_length=128, null=True, verbose_name='Тип загрузки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Тип загрузки автомобиля',
                'verbose_name_plural': 'Тип загрузки автомобилей',
            },
        ),
    ]
