# Generated by Django 4.1 on 2022-10-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_settypecar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setcolor',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car'),
        ),
    ]
