# Generated by Django 4.1 on 2022-10-10 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 22, 56, 55, 417545)),
        ),
    ]
