# Generated by Django 4.1 on 2022-10-15 07:07

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_adminentryfiles_distributorentryfiles_file_setentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminentryfiles',
            name='act',
            field=models.FileField(null=True, storage=core.models.AdminFileStorage(), upload_to='distributor/files/admin', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='adminentryfiles',
            name='agreement',
            field=models.FileField(null=True, storage=core.models.AdminFileStorage(), upload_to='distributor/files/admin', verbose_name='Соглашение'),
        ),
        migrations.AddField(
            model_name='adminentryfiles',
            name='bill',
            field=models.FileField(null=True, storage=core.models.AdminFileStorage(), upload_to='distributor/files/admin', verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='distributorentryfiles',
            name='act',
            field=models.FileField(null=True, storage=core.models.DistributorFileStorage(), upload_to='distributor/files/distributor', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='distributorentryfiles',
            name='agreement',
            field=models.FileField(null=True, storage=core.models.DistributorFileStorage(), upload_to='distributor/files/distributor', verbose_name='Соглашение'),
        ),
        migrations.AddField(
            model_name='distributorentryfiles',
            name='bill',
            field=models.FileField(null=True, storage=core.models.DistributorFileStorage(), upload_to='distributor/files/distributor', verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='setentry',
            name='admin_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminentryfiles', verbose_name='Файлы админа'),
        ),
        migrations.AddField(
            model_name='setentry',
            name='distributor_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.distributorentryfiles', verbose_name='Файлы дистрибьютора'),
        ),
    ]
