# Generated by Django 4.1 on 2022-10-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_adminentryfiles_act_adminentryfiles_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminentryfiles',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.entry'),
        ),
        migrations.AddField(
            model_name='distributorentryfiles',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.entry'),
        ),
    ]
