# Generated by Django 4.1 on 2022-10-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_adminentryfiles_entry_distributorentryfiles_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminentryfiles',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entry'),
        ),
        migrations.AlterField(
            model_name='distributorentryfiles',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entry'),
        ),
    ]
