# Generated by Django 4.1 on 2022-10-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_adminentryfiles_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminentryfiles',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.entry'),
        ),
        migrations.AddField(
            model_name='distributorentryfiles',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.entry'),
        ),
    ]
