# Generated by Django 4.1 on 2022-10-17 08:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_adminentryfiles_entry_distributorentryfiles_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminentryfiles',
            name='act',
            field=models.FileField(blank=True, default=None, storage=core.models.AdminFileStorage(), upload_to='distributor/files/admin', verbose_name='Акт'),
        ),
        migrations.AlterField(
            model_name='adminentryfiles',
            name='agreement',
            field=models.FileField(blank=True, default=None, storage=core.models.AdminFileStorage(), upload_to='distributor/files/admin', verbose_name='Соглашение'),
        ),
        migrations.AlterField(
            model_name='adminentryfiles',
            name='bill',
            field=models.FileField(blank=True, default=None, storage=core.models.AdminFileStorage(), upload_to='distributor/files/admin', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='distributorentryfiles',
            name='act',
            field=models.FileField(blank=True, default=None, storage=core.models.DistributorFileStorage(), upload_to='distributor/files/distributor', verbose_name='Акт'),
        ),
        migrations.AlterField(
            model_name='distributorentryfiles',
            name='agreement',
            field=models.FileField(blank=True, default=None, storage=core.models.DistributorFileStorage(), upload_to='distributor/files/distributor', verbose_name='Соглашение'),
        ),
        migrations.AlterField(
            model_name='distributorentryfiles',
            name='bill',
            field=models.FileField(blank=True, default=None, storage=core.models.DistributorFileStorage(), upload_to='distributor/files/distributor', verbose_name='Счёт'),
        ),
    ]
