# Generated by Django 4.1 on 2022-10-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_adminentryfiles_act_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminentryfiles',
            options={'verbose_name': 'Файл админа', 'verbose_name_plural': 'Файлы админов'},
        ),
        migrations.AlterModelOptions(
            name='distributorentryfiles',
            options={'verbose_name': 'Файл дистрибьютора', 'verbose_name_plural': 'Файлы дистрибьюторов'},
        ),
        migrations.AlterModelOptions(
            name='setcolor',
            options={'verbose_name': 'Цветовое соотношение', 'verbose_name_plural': 'Цветовые соотношения'},
        ),
        migrations.AddField(
            model_name='setentry',
            name='status',
            field=models.CharField(choices=[('new', 'When entry is created.'), ('work', 'When entry in work.'), ('complete', 'When entry is completed.')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='adminentryfiles',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.entry', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='distributorentryfiles',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.entry', verbose_name='Заявка'),
        ),
    ]
