# Generated by Django 4.1 on 2022-10-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_adminentryfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setentry',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('work', 'В работе'), ('complete', 'Завершена')], default='new', max_length=32, verbose_name='Статус заявки'),
        ),
    ]
