# Generated by Django 4.1 on 2022-11-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_setentry_is_shipped_alter_setentry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setentry',
            name='is_shipped',
        ),
    ]
